// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osmmltgrwtwddlqlkiql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zbW1sdGdyd3R3ZGRscWxraXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTE3MTYsImV4cCI6MjA2MzI4NzcxNn0.WIoweYtBGGE-06WKKZjQCfn1lNRp1-6EKMIRZ8AEHX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);